---
- name: install pypdfocr dependencies
  apt: "pkg={{ item }} state=latest"
  with_items:
    - 'python-dev'
    - 'ghostscript'
    - 'poppler-utils'
    - 'imagemagick'
    - 'build-essential'
    - 'libpng12-dev'
    - 'libjpeg62-dev'
    - 'zlib1g-dev'
    - 'libicu-dev'
    - 'libpango1.0-dev'
    - 'libcairo2-dev'
